# Generated by Django 4.2.7 on 2025-12-27 15:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movement_type', models.CharField(choices=[('in', 'Stok Girişi'), ('out', 'Stok Çıkışı'), ('adjustment', 'Düzeltme')], max_length=20, verbose_name='Hareket Tipi')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Miktar')),
                ('reason', models.TextField(verbose_name='Sebep/Açıklama')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='İşlem Tarihi')),
                ('performed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_movements', to=settings.AUTH_USER_MODEL, verbose_name='İşlemi Yapan')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_movements', to='products.product', verbose_name='Ürün')),
            ],
            options={
                'verbose_name': 'Stok Hareketi',
                'verbose_name_plural': 'Stok Hareketleri',
                'db_table': 'stock_movements',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StockAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minimum_quantity', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Minimum Stok Miktarı')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif mi?')),
                ('alert_sent', models.BooleanField(default=False, verbose_name='Uyarı Gönderildi mi?')),
                ('alert_sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Uyarı Gönderim Zamanı')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturma Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi')),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stock_alert', to='products.product', verbose_name='Ürün')),
            ],
            options={
                'verbose_name': 'Stok Uyarısı',
                'verbose_name_plural': 'Stok Uyarıları',
                'db_table': 'stock_alerts',
            },
        ),
        migrations.CreateModel(
            name='SaleToWebsite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('listed_quantity', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='İlan Edilen Miktar')),
                ('listed_price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='İlan Fiyatı')),
                ('status', models.CharField(choices=[('pending', 'Beklemede'), ('listed', 'İlanda'), ('sold', 'Satıldı'), ('removed', 'İlandan Kaldırıldı')], default='pending', max_length=20, verbose_name='Durum')),
                ('notes', models.TextField(blank=True, verbose_name='Notlar')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturma Tarihi')),
                ('listed_at', models.DateTimeField(blank=True, null=True, verbose_name='İlan Tarihi')),
                ('sold_at', models.DateTimeField(blank=True, null=True, verbose_name='Satış Tarihi')),
                ('listed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_listings', to=settings.AUTH_USER_MODEL, verbose_name='İlanı Oluşturan')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sale_listings', to='products.product', verbose_name='Ürün')),
                ('stock_movement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sale_listings', to='stock.stockmovement', verbose_name='İlişkili Stok Hareketi')),
            ],
            options={
                'verbose_name': 'Web Sitesi Satış İlanı',
                'verbose_name_plural': 'Web Sitesi Satış İlanları',
                'db_table': 'sale_to_website',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='stockmovement',
            index=models.Index(fields=['product'], name='stock_movem_product_911dad_idx'),
        ),
        migrations.AddIndex(
            model_name='stockmovement',
            index=models.Index(fields=['movement_type'], name='stock_movem_movemen_d922c9_idx'),
        ),
        migrations.AddIndex(
            model_name='stockmovement',
            index=models.Index(fields=['performed_by'], name='stock_movem_perform_e193c8_idx'),
        ),
        migrations.AddIndex(
            model_name='stockmovement',
            index=models.Index(fields=['-created_at'], name='stock_movem_created_8de937_idx'),
        ),
        migrations.AddIndex(
            model_name='stockalert',
            index=models.Index(fields=['product'], name='stock_alert_product_6816f8_idx'),
        ),
        migrations.AddIndex(
            model_name='stockalert',
            index=models.Index(fields=['is_active'], name='stock_alert_is_acti_ef8559_idx'),
        ),
        migrations.AddIndex(
            model_name='saletowebsite',
            index=models.Index(fields=['product'], name='sale_to_web_product_754506_idx'),
        ),
        migrations.AddIndex(
            model_name='saletowebsite',
            index=models.Index(fields=['status'], name='sale_to_web_status_70d347_idx'),
        ),
        migrations.AddIndex(
            model_name='saletowebsite',
            index=models.Index(fields=['listed_by'], name='sale_to_web_listed__7b999d_idx'),
        ),
        migrations.AddIndex(
            model_name='saletowebsite',
            index=models.Index(fields=['-created_at'], name='sale_to_web_created_f3eed1_idx'),
        ),
    ]
