# Generated by Django 4.2.7 on 2025-12-27 15:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif mi?')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Başlangıç Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Son Mesaj Tarihi')),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buyer_conversations', to=settings.AUTH_USER_MODEL, verbose_name='Alıcı')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to='products.product', verbose_name='Ürün')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seller_conversations', to=settings.AUTH_USER_MODEL, verbose_name='Satıcı')),
            ],
            options={
                'verbose_name': 'Konuşma',
                'verbose_name_plural': 'Konuşmalar',
                'db_table': 'conversations',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_text', models.TextField(verbose_name='Mesaj')),
                ('is_read', models.BooleanField(default=False, verbose_name='Okundu mu?')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='Okunma Zamanı')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Gönderim Zamanı')),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='conversations.conversation', verbose_name='Konuşma')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to=settings.AUTH_USER_MODEL, verbose_name='Gönderen')),
            ],
            options={
                'verbose_name': 'Mesaj',
                'verbose_name_plural': 'Mesajlar',
                'db_table': 'messages',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['conversation'], name='messages_convers_8904b4_idx'), models.Index(fields=['sender'], name='messages_sender__6ae55a_idx'), models.Index(fields=['is_read'], name='messages_is_read_6a69c0_idx'), models.Index(fields=['-created_at'], name='messages_created_17cff9_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['buyer'], name='conversatio_buyer_i_86e4f4_idx'),
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['seller'], name='conversatio_seller__8ef8ca_idx'),
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['product'], name='conversatio_product_bbd0a4_idx'),
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['-updated_at'], name='conversatio_updated_c163ba_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='conversation',
            unique_together={('product', 'buyer', 'seller')},
        ),
    ]
