# Generated by Django 5.1 on 2026-02-09 08:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=6, verbose_name='Doğrulama Kodu')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('expires_at', models.DateTimeField(verbose_name='Son Kullanma Tarihi')),
                ('is_used', models.BooleanField(default=False, verbose_name='Kullanıldı mı?')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verification_codes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Email Doğrulama',
                'verbose_name_plural': 'Email Doğrulamalar',
                'db_table': 'email_verifications',
                'ordering': ['-created_at'],
            },
        ),
    ]
