# Generated by Django 4.2.7 on 2025-12-27 15:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255, verbose_name='Firma Adı')),
                ('tax_number', models.CharField(max_length=50, unique=True, verbose_name='Vergi Numarası')),
                ('city', models.CharField(max_length=100, verbose_name='Şehir')),
                ('district', models.CharField(blank=True, max_length=100, verbose_name='İlçe')),
                ('phone', models.CharField(max_length=20, verbose_name='Telefon')),
                ('email', models.EmailField(max_length=254, verbose_name='E-posta')),
                ('is_verified', models.BooleanField(default=False, verbose_name='Doğrulanmış mı?')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Kayıt Tarihi')),
                ('owner_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='owned_company', to=settings.AUTH_USER_MODEL, verbose_name='Firma Sahibi')),
            ],
            options={
                'verbose_name': 'Firma',
                'verbose_name_plural': 'Firmalar',
                'db_table': 'companies',
            },
        ),
        migrations.CreateModel(
            name='CompanyUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('admin', 'Yönetici'), ('warehouse_manager', 'Depo Sorumlusu'), ('sales_staff', 'Satış Yetkilisi'), ('viewer', 'Görüntüleyici')], default='viewer', max_length=30, verbose_name='Rol')),
                ('joined_at', models.DateTimeField(auto_now_add=True, verbose_name='Katılma Tarihi')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_users', to='companies.company', verbose_name='Firma')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_memberships', to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı')),
            ],
            options={
                'verbose_name': 'Firma Çalışanı',
                'verbose_name_plural': 'Firma Çalışanları',
                'db_table': 'company_users',
                'indexes': [models.Index(fields=['company', 'user'], name='company_use_company_ae7570_idx'), models.Index(fields=['role'], name='company_use_role_2e6145_idx')],
                'unique_together': {('company', 'user')},
            },
        ),
        migrations.AddIndex(
            model_name='company',
            index=models.Index(fields=['owner_user'], name='companies_owner_u_9ab779_idx'),
        ),
        migrations.AddIndex(
            model_name='company',
            index=models.Index(fields=['city'], name='companies_city_499638_idx'),
        ),
        migrations.AddIndex(
            model_name='company',
            index=models.Index(fields=['is_verified'], name='companies_is_veri_16da10_idx'),
        ),
        migrations.AddIndex(
            model_name='company',
            index=models.Index(fields=['tax_number'], name='companies_tax_num_172cb7_idx'),
        ),
    ]
