# Generated by Django 4.2.7 on 2026-01-27 13:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='İl Adı')),
                ('plate_code', models.CharField(max_length=2, unique=True, verbose_name='Plaka Kodu')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
            ],
            options={
                'verbose_name': 'İl',
                'verbose_name_plural': 'İller',
                'db_table': 'cities',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='İlçe Adı')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='districts', to='addresses.city', verbose_name='İl')),
            ],
            options={
                'verbose_name': 'İlçe',
                'verbose_name_plural': 'İlçeler',
                'db_table': 'districts',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_type', models.CharField(choices=[('shipping', 'Teslimat Adresi'), ('billing', 'Fatura Adresi'), ('both', 'Her İkisi')], default='both', max_length=10, verbose_name='Adres Tipi')),
                ('title', models.CharField(max_length=100, verbose_name='Adres Başlığı')),
                ('full_name', models.CharField(max_length=200, verbose_name='Ad Soyad')),
                ('phone', models.CharField(max_length=20, verbose_name='Telefon')),
                ('neighborhood', models.CharField(blank=True, max_length=100, verbose_name='Mahalle')),
                ('address_line', models.TextField(verbose_name='Adres')),
                ('postal_code', models.CharField(blank=True, max_length=10, verbose_name='Posta Kodu')),
                ('is_default', models.BooleanField(default=False, verbose_name='Varsayılan')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='addresses.city', verbose_name='İl')),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='addresses.district', verbose_name='İlçe')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı')),
            ],
            options={
                'verbose_name': 'Adres',
                'verbose_name_plural': 'Adresler',
                'db_table': 'addresses',
                'ordering': ['-is_default', '-created_at'],
            },
        ),
    ]
