# Generated by Django 4.2.7 on 2025-12-27 15:40

import django.contrib.postgres.fields
import django.contrib.postgres.indexes
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Kategori Adı')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
                ('display_order', models.PositiveIntegerField(db_index=True, default=0, verbose_name='Sıralama')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturma Tarihi')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subcategories', to='products.category', verbose_name='Üst Kategori')),
            ],
            options={
                'verbose_name': 'Kategori',
                'verbose_name_plural': 'Kategoriler',
                'db_table': 'categories',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255, verbose_name='Ürün Adı')),
                ('description', models.TextField(verbose_name='Açıklama')),
                ('condition', models.IntegerField(choices=[(0, 'Sıfır / Hiç Kullanılmamış'), (1, 'Az Kullanılmış / İyi Durumda'), (2, 'Kullanılmış / Orta Durumda')], db_index=True, default=0, verbose_name='Kullanım Durumu')),
                ('stock_quantity', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Stok Miktarı')),
                ('sale_price', models.DecimalField(db_index=True, decimal_places=2, max_digits=12, verbose_name='Satış Fiyatı')),
                ('ai_suggested_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='AI Önerilen Fiyat')),
                ('city', models.CharField(db_index=True, max_length=100, verbose_name='Şehir')),
                ('district', models.CharField(blank=True, max_length=100, verbose_name='İlçe')),
                ('tags', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, help_text="Ör: ['demir', 'profil', '80x80']", null=True, size=None, verbose_name='Etiketler')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Aktif mi?')),
                ('is_sold', models.BooleanField(db_index=True, default=False, verbose_name='Satıldı mı?')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='İlan Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='products.category', verbose_name='Kategori')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='companies.company', verbose_name='Satıcı Firma')),
            ],
            options={
                'verbose_name': 'Ürün',
                'verbose_name_plural': 'Ürünler',
                'db_table': 'products',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.ImageField(upload_to='products/%Y/%m/', verbose_name='Fotoğraf')),
                ('is_primary', models.BooleanField(db_index=True, default=False, verbose_name='Ana Fotoğraf')),
                ('display_order', models.PositiveIntegerField(default=0, verbose_name='Sıralama')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yüklenme Tarihi')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='products.product', verbose_name='Ürün')),
            ],
            options={
                'verbose_name': 'Ürün Fotoğrafı',
                'verbose_name_plural': 'Ürün Fotoğrafları',
                'db_table': 'product_images',
                'ordering': ['display_order', '-is_primary'],
                'indexes': [models.Index(fields=['product', 'is_primary'], name='product_ima_product_c8c86a_idx'), django.contrib.postgres.indexes.BTreeIndex(fields=['product', 'display_order'], name='product_ima_product_ed7fcf_btree')],
            },
        ),
        migrations.AddConstraint(
            model_name='productimage',
            constraint=models.UniqueConstraint(condition=models.Q(('is_primary', True)), fields=('product',), name='one_primary_image_per_product'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['company'], name='products_company_7fb65d_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['category'], name='products_categor_4083ff_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['city'], name='products_city_b90800_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['is_active', 'is_sold'], name='products_is_acti_7f27ca_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['-created_at'], name='products_created_a77fb9_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=django.contrib.postgres.indexes.BTreeIndex(fields=['city', 'category', '-created_at'], name='products_city_fcad94_btree'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=django.contrib.postgres.indexes.BTreeIndex(fields=['is_active', 'is_sold', '-created_at'], name='products_is_acti_0ec3d6_btree'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=django.contrib.postgres.indexes.BTreeIndex(fields=['sale_price', '-created_at'], name='products_sale_pr_3403e4_btree'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=django.contrib.postgres.indexes.GinIndex(fields=['tags'], name='products_tags_29b04a_gin'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.CheckConstraint(condition=models.Q(('stock_quantity__gte', 0)), name='stock_quantity_positive'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.CheckConstraint(condition=models.Q(('sale_price__gt', 0)), name='sale_price_positive'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['parent'], name='categories_parent__7983b2_idx'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['slug'], name='categories_slug_b4303a_idx'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=django.contrib.postgres.indexes.BTreeIndex(fields=['display_order', 'name'], name='categories_display_a1187a_btree'),
        ),
    ]
